In [3]:
import pandas as pd

yield_data= pd.read_csv("../data/crop_yield.csv.zip")

yield_data.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [4]:
import pandas as pd
yield_data = pd.read_csv("../data/crop_yield.csv.zip")
yield_data.shape
yield_data.describe()
yield_data.info()
yield_data.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Crop             19689 non-null  str
 1   Crop_Year        19689 non-null  int64
 2   Season           19689 non-null  str
 3   State            19689 non-null  str
 4   Area             19689 non-null  float64
 5   Production       19689 non-null  int64
 6   Annual_Rainfall  19689 non-null  float64
 7   Fertilizer       19689 non-null  float64
 8   Pesticide        19689 non-null  float64
 9   Yield            19689 non-null  float64
dtypes: float64(5), int64(2), str(3)
memory usage: 1.5 MB

Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Yield              0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
crop_encoder = LabelEncoder()
season_encoder = LabelEncoder()
state_encoder = LabelEncoder()
yield_data['Crop'] = crop_encoder.fit_transform(yield_data['Crop'])
yield_data['Season'] = season_encoder.fit_transform(yield_data['Season'])
yield_data['State'] = state_encoder.fit_transform(yield_data['State'])
yield_data.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,0,1997,4,2,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,1,1997,1,2,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,8,1997,1,2,796.0,22,2051.4,75755.32,246.76,0.238333
3,9,1997,4,2,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,11,1997,1,2,1739.0,794,2051.4,165500.63,539.09,0.420909

In [6]:
x = yield_data.drop('Yield', axis=1)
y = yield_data['Yield']

print(x.head())
print(y.head())

   Crop  Crop_Year  Season  State     Area  Production  Annual_Rainfall  \
0     0       1997       4      2  73814.0       56708           2051.4
1     1       1997       1      2   6637.0        4685           2051.4
2     8       1997       1      2    796.0          22           2051.4
3     9       1997       4      2  19656.0   126905000           2051.4
4    11       1997       1      2   1739.0         794           2051.4

   Fertilizer  Pesticide
0  7024878.38   22882.34
1   631643.29    2057.47
2    75755.32     246.76
3  1870661.52    6093.36
4   165500.63     539.09
0       0.796087
1       0.710435
2       0.238333
3    5238.051739
4       0.420909
Name: Yield, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print(x_train.shape)
print(x_test.shape)

(15751, 9)
(3938, 9)

In [8]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=50, random_state=42)
model.fit(x_train, y_train)
print("Model training completed.")

Model training completed.

In [9]:
from sklearn.metrics import mean_absolute_error, r2_score

predictions = model.predict(x_test)
mae = mean_absolute_error(y_test, predictions)

r2 = r2_score(y_test, predictions)
print(f"Mean Absolute Error: {mae}")
print(f"R^2 Score: {r2}")

Mean Absolute Error: 10.887269145806371
R^2 Score: 0.9055999798800722

In [10]:
import joblib
joblib.dump(model, "../models/yield_model.pkl")
joblib.dump(crop_encoder, "../models/crop_encoder.pkl")
joblib.dump(season_encoder, "../models/season_encoder.pkl")
joblib.dump(state_encoder, "../models/state_encoder.pkl")
print("Model and encoders saved successfully!")

Model and encoders saved successfully!

In [11]:
import os
print("mb=", os.path.getsize("../models/yield_model.pkl") / (1024 * 1024), "MB")

mb= 66.66746616363525 MB