In [28]:
import pandas as pd

soil_data = pd.read_csv("../data/Fertilizer Prediction.csv")
soil_data.head()

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26,52,38,Sandy,Maize,37,0,0,Urea
1,29,52,45,Loamy,Sugarcane,12,0,36,DAP
2,34,65,62,Black,Cotton,7,9,30,14-35-14
3,32,62,34,Red,Tobacco,22,0,20,28-28
4,28,54,46,Clayey,Paddy,35,0,0,Urea

In [29]:
soil_data.shape
soil_data.info()
soil_data.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Temparature      99 non-null     int64
 1   Humidity         99 non-null     int64
 2   Moisture         99 non-null     int64
 3   Soil Type        99 non-null     str
 4   Crop Type        99 non-null     str
 5   Nitrogen         99 non-null     int64
 6   Potassium        99 non-null     int64
 7   Phosphorous      99 non-null     int64
 8   Fertilizer Name  99 non-null     str
dtypes: int64(6), str(3)
memory usage: 7.1 KB

Temparature        0
Humidity           0
Moisture           0
Soil Type          0
Crop Type          0
Nitrogen           0
Potassium          0
Phosphorous        0
Fertilizer Name    0
dtype: int64

In [30]:
from sklearn.preprocessing import LabelEncoder

fertilizer_encoder = LabelEncoder()
soil_encoder = LabelEncoder()
crop_encoder = LabelEncoder()

soil_data["Fertilizer Name"] = fertilizer_encoder.fit_transform(soil_data["Fertilizer Name"])

soil_data["Soil Type"] = soil_encoder.fit_transform(soil_data["Soil Type"])

soil_data["Crop Type"] = crop_encoder.fit_transform(soil_data["Crop Type"])
soil_data.head()

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26,52,38,4,3,37,0,0,6
1,29,52,45,2,8,12,0,36,5
2,34,65,62,0,1,7,9,30,1
3,32,62,34,3,9,22,0,20,4
4,28,54,46,1,6,35,0,0,6

In [31]:
X = soil_data.drop("Fertilizer Name", axis=1)
y = soil_data["Fertilizer Name"]

print(X.shape)
print(y.shape)

(99, 8)
(99,)

In [32]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(x_train.shape)
print(x_test.shape)

(79, 8)
(20, 8)

In [33]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(x_train, y_train)

print("Fertilizer model trained!")

Fertilizer model trained!

In [34]:
from sklearn.metrics import accuracy_score

predictions = model.predict(x_test)

accuracy = accuracy_score(y_test, predictions)

print(f"Accuracy: {accuracy}")

Accuracy: 0.95

In [36]:
print(fertilizer_encoder.classes_)
print(soil_encoder.classes_)
print(crop_encoder.classes_)

['10-26-26' '14-35-14' '17-17-17' '20-20' '28-28' 'DAP' 'Urea']
['Black' 'Clayey' 'Loamy' 'Red' 'Sandy']
['Barley' 'Cotton' 'Ground Nuts' 'Maize' 'Millets' 'Oil seeds' 'Paddy'
 'Pulses' 'Sugarcane' 'Tobacco' 'Wheat']

In [ ]:
#sample 1
sample = [[32, 60, 40, 3, 2, 10, 5, 20]]
prediction = model.predict(sample)
fertilizer = fertilizer_encoder.inverse_transform(prediction)
print(fertilizer)

c:\Users\Lenovo\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

['14-35-14']

In [38]:
#sample 2
sample = [[35, 70, 60, 0, 1, 4, 15, 10]]

prediction = model.predict(sample)
fertilizer = fertilizer_encoder.inverse_transform(prediction)

print(fertilizer)

c:\Users\Lenovo\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

['17-17-17']

In [39]:
#sample 3
sample = [[28, 55, 30, 4, 10, 30, 2, 35]]

prediction = model.predict(sample)
fertilizer = fertilizer_encoder.inverse_transform(prediction)

print(fertilizer)

['Urea']

c:\Users\Lenovo\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [40]:
import joblib
joblib.dump(model, "../models/fertilizer_model.pkl")
joblib.dump(fertilizer_encoder, "../models/fertilizer_encoder.pkl")
print("Model and encoders saved!")

Model and encoders saved!